# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ad3e868699e2399e8d139738494dea88e3eda47eb42cf192cded0aa02c9050f307298490544f7873510186e1f5d9bb48b3b6dd58f729e06d58293f9bb65473f

test:
  secret_key_base: a15c0c34d79cab9676c95cbe0efb62bd0a3bc4030d6168dc26a96b6509d4ef62167e6f4ec3650b81267d3d34f57237326c098cfadc4fdcf79714fe6dc93cc66e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
